[package]
name = "guest-r0"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
common = { path = "../../common", features = ["r0"] }
risc0-zkvm = { version = "1.0.0-rc.5", default-features = false, features = ['std'] }

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"
