[package]
name = "guest-r0"
version = { workspace = true }
edition = { workspace = true }

[build-dependencies]
risc0-build = { version = "1.0.0-rc.5" }

[package.metadata.risc0]
methods = ["guest-r0"]